
import { Book, Masterclass, ContactInfo, SubscriptionPlan, StoreBook, AppConfig, FAQItem } from './types';

export const DEFAULT_APP_CONFIG: AppConfig = {
  appName: 'BookBites',
  appSlogan: 'Read less, learn more.',
  appLogoUrl: '', // Empty means use default icon
  onlyMeMode: false
};

export const CATEGORIES = [
  'Business', 'Psychology', 'Self-Help', 'Science', 'Productivity', 'Biography', 'Leadership', 'Creative'
];

export const INITIAL_CONTACT_INFO: ContactInfo = {
  phone: '+998 90 123 45 67',
  email: 'info@bookbites.uz',
  address: 'Tashkent, Uzbekistan, Amir Temur 108',
  website: 'www.bookbites.uz',
  checkoutUrl: 'https://example.com/checkout/all',
  mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2996.3639446415!2d69.2786!3d41.325!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDHCsDE5JzMwLjAiTiA2OcKwMTYnNDMuMCJF!5e0!3m2!1sen!2s!4v1600000000000!5m2!1sen!2s',
  telegramUrl: 'https://t.me/bookbites_channel',
  instagramUrl: 'https://instagram.com/bookbites',
  telegramAdminUrl: 'https://t.me/admin_user'
};

export const MOCK_FAQS: FAQItem[] = [
    { id: '1', question: 'Dasturdan qanday foydalaniladi?', answer: 'Dasturga kiring, kitobni tanlang va o\'qish yoki tinglashni boshlang.' },
    { id: '2', question: 'Premium obuna nima beradi?', answer: 'Premium obuna barcha kitoblar va audio formatlarga cheksiz kirish imkonini beradi.' }
];

export const INITIAL_PLANS: SubscriptionPlan[] = [
  {
    id: 'free',
    name: 'Free Starter',
    price: '$0',
    period: '/forever',
    features: ['Access to Free Summaries', 'Create 1 Bookshelf', 'Basic Support'],
    paymentLink: '#',
    active: true
  },
  {
    id: 'premium',
    name: 'Premium',
    price: '$4.99',
    period: '/month',
    features: ['Unlimited Reading', 'Audio Summaries', 'Offline Mode', 'No Ads'],
    paymentLink: 'https://example.com/checkout/premium',
    active: true
  },
  {
    id: 'gold',
    name: 'Gold',
    price: '$49.99',
    period: '/year',
    features: ['All Premium Features', 'Exclusive Gold Masterclasses', 'Priority Support', 'Early Access'],
    paymentLink: 'https://example.com/checkout/gold',
    active: true
  }
];

export const TRANSLATIONS = {
  en: {
    home: "Home",
    search: "Search",
    masterclass: "Masterclass",
    library: "Library",
    settings: "Settings",
    admin: "Admin",
    discover: "Discover",
    goodMorning: "Good Morning",
    trending: "Trending Now",
    newArrivals: "New Arrivals",
    recommended: "Recommended for You",
    explore: "Explore",
    myLibrary: "My Library",
    savedForLater: "Saved For Later",
    bookshelves: "Bookshelves",
    newShelf: "New Shelf",
    read: "Read",
    listen: "Listen",
    aboutBook: "About this book",
    startReading: "Start Reading",
    premiumContent: "Premium Content",
    goldContent: "Gold Exclusive",
    unlockNow: "Unlock Now",
    darkMode: "Dark Mode",
    notifications: "Notifications",
    help: "Help & Support",
    faq: "F.A.Q",
    contactUs: "Contact Us",
    logOut: "Log Out",
    language: "Language",
    saveTo: "Save to Shelf",
    cancel: "Cancel",
    save: "Save",
    sendMessage: "Send Message",
    yourName: "Your Name",
    yourMessage: "Your Message",
    messageSent: "Message Sent!",
    adminDashboard: "Admin Dashboard",
    messages: "Messages",
    totalBooks: "Total Books",
    premium: "Premium",
    gold: "Gold",
    free: "Free",
    noAudio: "No audio version available.",
    playingChapter: "Playing Chapter 1",
    shelfName: "Shelf Name",
    signIn: "Sign In",
    signUp: "Sign Up",
    continueGuest: "Continue as Guest",
    phone: "Phone Number",
    password: "Password",
    orGoogle: "Or continue with Google",
    watch: "Watch",
    instructor: "Instructor",
    bookOfTheWeek: "Book of the Week",
    contactInfo: "Contact Info",
    email: "Email",
    address: "Address",
    website: "Website",
    bookstore: "Bookstore",
    myCart: "My Cart",
    favorites: "Favorites",
    buy: "Buy",
    addToCart: "Add",
    buyAll: "Buy All",
    backToApp: "Back to App",
    all: "All",
    featured: "Featured",
    callUs: "Call Us",
    openMap: "Open Map",
    socials: "Social Networks",
    adminTelegram: "Admin Telegram",
    plans: {
        free: { name: "Free Starter", period: "/forever", features: ["Access to Free Summaries", "Create 1 Bookshelf", "Basic Support"] },
        premium: { name: "Premium", period: "/month", features: ["Unlimited Reading", "Audio Summaries", "Offline Mode", "No Ads"] },
        gold: { name: "Gold", period: "/year", features: ["All Premium Features", "Exclusive Gold Masterclasses", "Priority Support", "Early Access"] }
    }
  },
  ru: {
    home: "Главная",
    search: "Поиск",
    masterclass: "Мастер-класс",
    library: "Библиотека",
    settings: "Настройки",
    admin: "Админ",
    discover: "Обзор",
    goodMorning: "Доброе утро",
    trending: "В тренде",
    newArrivals: "Новинки",
    recommended: "Рекомендовано для вас",
    explore: "Поиск",
    myLibrary: "Моя библиотека",
    savedForLater: "Сохраненное",
    bookshelves: "Полки",
    newShelf: "Новая полка",
    read: "Читать",
    listen: "Слушать",
    aboutBook: "О книге",
    startReading: "Читать",
    premiumContent: "Премиум контент",
    goldContent: "Gold Эксклюзив",
    unlockNow: "Разблокировать",
    darkMode: "Темная тема",
    notifications: "Уведомления",
    help: "Помощь",
    faq: "F.A.Q",
    contactUs: "Контакты",
    logOut: "Выйти",
    language: "Язык",
    saveTo: "Сохранить на полку",
    cancel: "Отмена",
    save: "Сохранить",
    sendMessage: "Отправить",
    yourName: "Ваше имя",
    yourMessage: "Сообщение",
    messageSent: "Отправлено!",
    adminDashboard: "Панель Админа",
    messages: "Сообщения",
    totalBooks: "Всего книг",
    premium: "Премиум",
    gold: "Gold",
    free: "Бесплатно",
    noAudio: "Аудио версия недоступна.",
    playingChapter: "Глава 1",
    shelfName: "Название полки",
    signIn: "Войти",
    signUp: "Регистрация",
    continueGuest: "Продолжить как гость",
    phone: "Номер телефона",
    password: "Пароль",
    orGoogle: "Или через Google",
    watch: "Смотреть",
    instructor: "Инструктор",
    bookOfTheWeek: "Книга недели",
    contactInfo: "Контактная информация",
    email: "Email",
    address: "Адрес",
    website: "Веб-сайт",
    bookstore: "Магазин",
    myCart: "Корзина",
    favorites: "Избранное",
    buy: "Купить",
    addToCart: "В корзину",
    buyAll: "Купить все",
    backToApp: "Назад в приложение",
    all: "Все",
    featured: "Рекомендуем",
    callUs: "Позвонить",
    openMap: "Открыть карту",
    socials: "Социальные сети",
    adminTelegram: "Админ Telegram",
    plans: {
        free: { name: "Bepul Start", period: "/abadiy", features: ["Bepul xulosalarni o'qish", "1 ta kitob javoni", "Asosiy yordam"] },
        premium: { name: "Premium", period: "/oyiga", features: ["Cheksiz o'qish", "Audio xulosalar", "Oflayn rejim", "Reklamasiz"] },
        gold: { name: "Gold", period: "/yiliga", features: ["Barcha Premium imkoniyatlar", "Maxsus Gold Master-klasslar", "Tezkor yordam", "Ertalabki kirish"] }
    }
  },
  uz: {
    home: "Asosiy",
    search: "Qidiruv",
    masterclass: "Master-klass",
    library: "Kutubxona",
    settings: "Sozlamalar",
    admin: "Admin",
    discover: "Bosh sahifa",
    goodMorning: "Xayrli tong",
    trending: "Trendda",
    newArrivals: "Yangi kelganlar",
    recommended: "Siz uchun tavsiya",
    explore: "Izlash",
    myLibrary: "Kutubxonam",
    savedForLater: "Saqlanganlar",
    bookshelves: "Javonlar",
    newShelf: "Yangi javon",
    read: "O'qish",
    listen: "Tinglash",
    aboutBook: "Kitob haqida",
    startReading: "O'qishni boshlash",
    premiumContent: "Premium Tarkib",
    goldContent: "Gold Maxsus",
    unlockNow: "Ochish",
    darkMode: "Tun rejimi",
    notifications: "Bildirishnomalar",
    help: "Yordam",
    faq: "F.A.Q",
    contactUs: "Bog'lanish",
    logOut: "Chiqish",
    language: "Til",
    saveTo: "Javonga saqlash",
    cancel: "Bekor qilish",
    save: "Saqlash",
    sendMessage: "Xabar yuborish",
    yourName: "Ismingiz",
    yourMessage: "Xabaringiz",
    messageSent: "Xabar yuborildi!",
    adminDashboard: "Admin Paneli",
    messages: "Xabarlar",
    totalBooks: "Jami kitoblar",
    premium: "Premium",
    gold: "Gold",
    free: "Bepul",
    noAudio: "Audio versiya mavjud emas.",
    playingChapter: "1-bob o'ynalmoqda",
    shelfName: "Javon nomi",
    signIn: "Kirish",
    signUp: "Ro'yxatdan o'tish",
    continueGuest: "Mehmon sifatida davom etish",
    phone: "Telefon raqami",
    password: "Parol",
    orGoogle: "Google orqali",
    watch: "Ko'rish",
    instructor: "O'qituvchi",
    bookOfTheWeek: "Hafta kitobi",
    contactInfo: "Bog'lanish ma'lumotlari",
    email: "Email",
    address: "Manzil",
    website: "Veb-sayt",
    bookstore: "Do'kon",
    myCart: "Savat",
    favorites: "Tanlanganlar",
    buy: "Sotib olish",
    addToCart: "Qo'shish",
    buyAll: "Hammasini olish",
    backToApp: "Ilovaga qaytish",
    all: "Barcha kitoblar",
    featured: "Tavsiya etamiz",
    callUs: "Qo'ng'iroq qilish",
    openMap: "Xaritani ochish",
    socials: "Ijtimoiy tarmoqlar",
    adminTelegram: "Admin Telegram",
    plans: {
        free: { name: "Bepul Start", period: "/abadiy", features: ["Bepul xulosalarni o'qish", "1 ta kitob javoni", "Asosiy yordam"] },
        premium: { name: "Premium", period: "/oyiga", features: ["Cheksiz o'qish", "Audio xulosalar", "Oflayn rejim", "Reklamasiz"] },
        gold: { name: "Gold", period: "/yiliga", features: ["Barcha Premium imkoniyatlar", "Maxsus Gold Master-klasslar", "Tezkor yordam", "Ertalabki kirish"] }
    }
  }
};

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'Self-Help',
    coverImageUrl: 'https://picsum.photos/id/20/300/450',
    about: 'An easy and proven way to build good habits and break bad ones.',
    summaryText: `<h3>The Fundamentals of Atomic Habits</h3><p>Success is the product of daily habits...</p>`,
    duration: 12,
    createdAt: Date.now(),
    published: true,
    isFeatured: true,
    isPopular: true,
    isBookOfTheWeek: true,
    accessLevel: 'free',
  },
  {
    id: '2',
    title: 'Deep Work',
    author: 'Cal Newport',
    category: 'Productivity',
    coverImageUrl: 'https://picsum.photos/id/24/300/450',
    about: 'Rules for focused success in a distracted world.',
    summaryText: `<p>Deep work is the ability to focus without distraction...</p>`,
    duration: 15,
    createdAt: Date.now() - 100000,
    published: true,
    isPopular: true,
    accessLevel: 'premium',
  },
  {
    id: '3',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    category: 'Science',
    coverImageUrl: 'https://picsum.photos/id/28/300/450',
    about: 'A brief history of humankind.',
    summaryText: `<p>Three important revolutions shaped the course of history...</p>`,
    duration: 22,
    createdAt: Date.now() - 200000,
    published: true,
    isFeatured: true,
    accessLevel: 'gold',
  },
  {
    id: '4',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    category: 'Psychology',
    coverImageUrl: 'https://picsum.photos/id/36/300/450',
    about: 'The two systems that drive the way we think.',
    summaryText: `<p>System 1 operates automatically and quickly...</p>`,
    duration: 18,
    createdAt: Date.now() - 300000,
    published: true,
    accessLevel: 'premium',
  },
  {
    id: '5',
    title: 'Zero to One',
    author: 'Peter Thiel',
    category: 'Business',
    coverImageUrl: 'https://picsum.photos/id/42/300/450',
    about: 'Notes on startups, or how to build the future.',
    summaryText: `<p>Doing what we already know how to do takes the world from 1 to n...</p>`,
    duration: 10,
    createdAt: Date.now() - 400000,
    published: true,
    accessLevel: 'free',
  }
];

export const MOCK_STORE_BOOKS: StoreBook[] = [
    {
        id: 's1',
        title: 'The Psychology of Money',
        author: 'Morgan Housel',
        price: '$18.00',
        coverUrl: 'https://picsum.photos/id/101/300/450',
        about: 'Timeless lessons on wealth, greed, and happiness.',
        buyLink: 'https://example.com/buy/money',
        category: 'Business'
    },
    {
        id: 's2',
        title: 'Rich Dad Poor Dad',
        author: 'Robert Kiyosaki',
        price: '$12.50',
        coverUrl: 'https://picsum.photos/id/102/300/450',
        about: 'What the rich teach their kids about money.',
        buyLink: 'https://example.com/buy/rich',
        category: 'Business'
    },
    {
        id: 's3',
        title: 'Start With Why',
        author: 'Simon Sinek',
        price: '$15.99',
        coverUrl: 'https://picsum.photos/id/103/300/450',
        about: 'How great leaders inspire everyone to take action.',
        buyLink: 'https://example.com/buy/why',
        category: 'Leadership'
    },
    {
        id: 's4',
        title: 'Show Your Work!',
        author: 'Austin Kleon',
        price: '$10.00',
        coverUrl: 'https://picsum.photos/id/104/300/450',
        about: '10 ways to share your creativity and get discovered.',
        buyLink: 'https://example.com/buy/show',
        category: 'Creative'
    }
];

export const MOCK_MASTERCLASSES: Masterclass[] = [
  {
    id: 'm1',
    title: 'Scientific Thinking',
    instructor: 'Neil deGrasse Tyson',
    category: 'Science',
    thumbnailUrl: 'https://picsum.photos/id/48/400/225',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Learn how to think like a scientist...',
    duration: 45,
    accessLevel: 'premium'
  },
  {
    id: 'm2',
    title: 'Creative Writing',
    instructor: 'Margaret Atwood',
    category: 'Creative',
    thumbnailUrl: 'https://picsum.photos/id/60/400/225',
    videoUrl: '',
    description: 'The legendary author teaches you how to craft...',
    duration: 60,
    accessLevel: 'free'
  },
  {
    id: 'm3',
    title: 'Leadership Strategy',
    instructor: 'Bob Iger',
    category: 'Leadership',
    thumbnailUrl: 'https://picsum.photos/id/76/400/225',
    videoUrl: '',
    description: 'Learn business strategy and leadership...',
    duration: 50,
    accessLevel: 'gold'
  }
];
